### ISSUE TITLE
Импорт обработки через конфигуратор

### ISSUE THREAD

**Issue by nbeliaev** [KonstantinHeinrich/Color-Schemes-Installer-EDT-Format#1]
Добрый день
Пытаюсь собрать обработку из файлов через Конфигуратор. При импорте он хочет xml root file, но репозитории такого нет. Или же сборка может быть выполнено только из EDT?

**Comment by KonstantinHeinrich** [comment]
Добрый день
Эта репозиторий обработки в формате именно для EDT. Рядом лежит репозиторий в формате для Конфигуратора.
